### ISSUE TITLE
Tracking URL clicks for all links

### ISSUE THREAD

**Issue by ishanguliani** [ishanguliani/fake-post-injector-backend#1]
Currently there is no way to track if the user clicked on a particular link while scrolling their FB timeline. The only time click tracking happens is when the user is asked if they clicked a particular link while taking the survey. 

The proposed solution is to have the user click on a shortened proxy link so that the clicks can be counted. For instance, _https://www.youtube.com/hhf987hhfd_ will be replaced with _https://seng-research.com/trackClick/_ and a counter is incremented when the bounce happens. 

We should do this for both fake awa genuine link types

**Comment by ishanguliani** [comment]
# TODO

- [x] Add new field **short_link** to fake link model. This will store the shortened URL forms for the fake links entered by the admin at the time of new fake link creation
- [x] Re-process the existing fake link models to update the above field for them
- [x] Update the chrome extension code to use the above mentioned field **short_link** instead of using the older field **fake_link** while in action
- [x] Return **short_url_for_genuine_link** in the json response for `savePostToServer` API which denotes the short URL for the genuine link 
- [x] Update the chrome extension code to change the genuine link's anchor target to the above returned **short_url_for_genuine_link**
