### ISSUE TITLE
Generate report for link clicks

### ISSUE THREAD

**Issue by ishanguliani** [ishanguliani/fake-post-injector-backend#2]
For all link user interactions happening while scrolling the extension, generate the following reports in real time -

## Report showing user interaction summary
| User | Total # links seen so far | Total # links clicked so far|
| ------------- | ------------------| -------------------|
| Ishan Guliani | 25 | 4 |
| John Fletcher | 12 | 0 |
| Max Dean | 50 | 17 |

## Report showing user-link-click interaction
| User | Link (actual link user would route to if clicked) | Clicked on | link_type | original link replaced | Clicked? (Y for yes) |# clicks on this link | 
| ------------| --------------------------| --------------------------- | --- | -- |--| -- |
|Ishan Guliani|https://www.bbcnews.com| https://seng-research.com/jkhfdjk |genuine|-| Y| 1 |
|Ishan Guliani|https://www.newsusa.com| https://seng-research.com/aweoivl |fake|something.com|Y| 2 |
|Ishan Guliani|https://www.africanews.com| https://seng-research.com/kljadsnl | fake |something.com| NO| 0 |
|John Fletcher|https://www.youtube.com?video=dfcj897he1jfbkdvjyv9| https://seng-research.com/cxcsfbg | genuine |-| Y | 1 |

## TODO
- [x] Add a new section in the [admin panel](https://www.seng-research.com/admin) called **Reports** which will contain the above mentioned 2 reports namely -
  - [x] _Real time click counts_ (showing _how many_ links the user has seen or clicked in a session)
    - user - number of links seen - number of links clicked
  - [x] _User link interaction report_ (showing _what_ links the user was presented and what he did with them)
    - user - link type (genuine/fake) - link url - original link url (for links of type fake) - link short url - link_clicked (boolean) - number of times clicked
- [x] Add 3 new fields to the existing [LinkModel](https://seng-research.com/admin/link/linkmodel/)
  - [x] **is_clicked_event_from_ground_data** (this field will be set to `true` when the user clicks on the link during the facebook session). 
  NOTE: this is different from the existing field `is_clicked` in [LinkModel](https://seng-research.com/admin/link/linkmodel/) which denotes the link clicks from the user's _self reported survey data_. As discussed, the idea here is to keep these two pieces of information different to be able to draw more conclusions on the disparity between the ground and reported data in the future which is a little misty for now. 
  - [x] **is_clicked_event_from_ground_data_time** (this field will record the time of when the above event took place)

**Comment by ishanguliani** [comment]
In the table labelled `Report showing user-link-click interaction` above - I am no longer considering the last 2 columns - 
1. `Clicked? (Y for yes)` and 
2. `# clicks on this link`.

This is because all entries in this table are created as a result of a click. So there is no need to explicitly mark clicks and their counts.
